#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: onap-smo-lite
description: Lightweight ONAP SMO stack with SDNC web UI, SDNR controller, and SDNR database.
type: application
version: 0.3.0
appVersion: "1.0.0"
