{{- if and .Values.kafkaUi.enabled .Values.kafkaUi.ingress.enabled }}
##
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "kafka-ui") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
  {{- with .Values.kafkaUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.kafkaUi.ingress.className }}
  ingressClassName: {{ .Values.kafkaUi.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.kafkaUi.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "onap-smo-lite.componentName" (dict "root" $ "component" "kafka-ui") }}
                port:
                  number: {{ $.Values.kafkaUi.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.kafkaUi.ingress.tls }}
  tls:
    {{- toYaml .Values.kafkaUi.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
