#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnrdb
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
spec:
  type: {{ .Values.sdnrdb.service.type }}
  ports:
    - name: http
      port: {{ .Values.sdnrdb.service.port }}
      targetPort: http
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
