{{- if and .Values.sdnrdb.persistence.enabled (not .Values.sdnrdb.persistence.existingClaim) }}
#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnrdb
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
spec:
  accessModes:
    {{- toYaml .Values.sdnrdb.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.sdnrdb.persistence.size }}
  {{- if .Values.sdnrdb.persistence.storageClass }}
  storageClassName: {{ .Values.sdnrdb.persistence.storageClass }}
  {{- end }}
{{- end }}
