{{- if .Values.zookeeper.enabled }}
#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "zookeeper") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
  ports:
    - name: client
      port: {{ .Values.zookeeper.service.port }}
      targetPort: client
      protocol: TCP
{{- end }}
