{{- if .Values.zookeeper.enabled }}
#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "zookeeper") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "onap-smo-lite.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        {{- include "onap-smo-lite.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          command:
            - sh
            - -c
            - bin/zookeeper-server-start.sh config/zookeeper.properties
          ports:
            - name: client
              containerPort: {{ .Values.zookeeper.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.zookeeper.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.zookeeper.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if and .Values.kafka.enabled .Values.kafka.auth.enabled }}
            - name: KAFKA_OPTS
              value: >-
                -Djava.security.auth.login.config=/etc/zookeeper/secrets/jaas/zk_server_jaas.conf
                -Dzookeeper.kerberos.removeHostFromPrincipal=true
                -Dzookeeper.kerberos.removeRealmFromPrincipal=true
                -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                -Dzookeeper.requireClientAuthScheme=sasl
            {{- end }}
          volumeMounts:
            {{- if and .Values.kafka.enabled .Values.kafka.auth.enabled }}
            - name: zookeeper-jaas
              mountPath: /etc/zookeeper/secrets/jaas
            {{- end }}
          {{- with .Values.zookeeper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if and .Values.kafka.enabled .Values.kafka.auth.enabled }}
        - name: zookeeper-jaas
          configMap:
            name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "kafka-jaas") }}
            items:
              - key: zk_server_jaas.conf
                path: zk_server_jaas.conf
        {{- end }}
{{- end }}
