#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: linuxptp
description: Chart for deploying Linuxptp DaemonSet
kubeVersion: ">= 1.24.0-0"
icon: https://linuxptp.nwtime.org/images/logo.png
home: https://linuxptp.nwtime.org/
sources:
- https://github.com/richardcochran/linuxptp
keywords:
- linuxptp
- ptp4l
- phc2sys
- ptp
- srsran
type: application
version: 1.1.0
appVersion: "4.3.0"
