#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: srsran-cu-du
description: Official srsRAN Project CU/DU Helm Chart
kubeVersion: ">= 1.24.0-0"
icon: https://docs.srsran.com/en/latest/_static/logo.png
home: https://docs.srsran.com/projects/project/en/latest/
sources:
- https://github.com/srsran/srsran_project
keywords:
- srsran
- 5g
- oran
- vran
- gnb
- mobile
type: application
version: 2.2.0
appVersion: "25.04"
